---
- name: Gather facts for all hosts
  hosts: all
  gather_facts: true
  tasks:
    - name: Group hosts to determine when using --limit
      group_by:
        key: "all_using_limit_{{ (ansible_play_batch | length) != (groups['all'] | length) }}"

- name: Gather facts for all hosts (if using --limit)
  hosts: all_using_limit_True
  gather_facts: false
  vars:
    batch_index: "{{ ansible_play_batch.index(inventory_hostname) }}"
    batch_size: "{{ ansible_play_batch | length }}"
    delegate_hosts: "{{ groups['all'][batch_index | int::batch_size | int] }}"
  tasks:
    - name: Gather facts
      setup:
      delegate_facts: True
      delegate_to: "{{ item }}"
      with_items: "{{ delegate_hosts }}"
      when:
        - not hostvars[item].module_setup | default(false)
