- name: Copy containerd.conf
  template:
    src: containerd.conf.j2
    dest: /etc/modules-load.d/containerd.conf

- name: Load module overlay
  modprobe:
    name: overlay
    state : present

- name: Load module br_netfilter
  modprobe:
    name: br_netfilter
    state : present

- name: Copy 99-kubernetes-cri.conf
  template:
    src: 99-kubernetes-cri.conf.j2
    dest: /etc/sysctl.d/99-kubernetes-cri.conf

- name: Apply sysctl
  shell: sysctl --system

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Install containerd packages
  apt:
    name: containerd
    state: latest

- name: Create /etc/containerd directory
  file:
    path: /etc/containerd
    state: directory

- name: Create containerd configuration file
  shell: "containerd config default | sudo tee /etc/containerd/config.toml"

- name: Restart containerd service
  service:
    name: containerd
    enabled: yes
    state: restarted
